ledgered_parent/accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

ledgered_parent/ledgered/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ledgered_app.urls')),
    path('accounts/', include('accounts.urls')),
    #path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

ledgered_parent/ledgered_app/urls.py
"""Defines URL patterns for ledgered_app."""

from django.urls import path

from . import views

app_name = 'ledgered_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload', views.upload, name='upload'),
    path('ledger', views.ledger, name='ledger'),
    path('ledger_queue', views.ledger_queue, name='ledger_queue'),
    path('reports', views.reports, name='reports'),
    path('manage', views.manage, name='manage'),
    path('seed', views.seed, name='seed'),
    path('export', views.export, name='export'),

    # for debugging
    path('list_categories', views.CategoriesListView.as_view(template_name="ledgered_app/list_categories.html")
         , name='list_categories'),
    path('list_transactions', views.TransactionListView.as_view(template_name="ledgered_app/list_transactions.html")
         , name='list_transactions'),
    path('list_descriptions', views.DescriptionListView.as_view(template_name="ledgered_app/list_descriptions.html")
         , name='list_descriptions'),
    path('list_accounts', views.AccountListView.as_view(template_name="ledgered_app/list_accounts.html")
         , name='list_accounts'),

    path('delete_all', views.delete_all, name='delete_all')
]

ledgered_parent/ledgered_app/models.py
from django.db import models
from django.contrib.auth.models import User

TRANSACTION_TYPES = [
    ("Credit", "Credit"),
    ("Debit", "Debit")
]

PLUGINS = [
    ("Amazon", "Amazon"),
    ("Mint", "Mint"),
    ("Chase", "Chase"),
    ("Fidelity", "Fidelity")
]


def get_enum_values(nested_enum):
    """Returns the second value in each struct of an enum like PLUGINS or TRANSACTION_TYPES"""
    return [x[1] for x in nested_enum]


def get_enum_keys(nested_enum):
    """Returns the first value in each struct of an enum like PLUGINS or TRANSACTION_TYPES"""
    return [x[0] for x in nested_enum]


class Account(models.Model):
    name = models.CharField(
        max_length=100,
        choices=PLUGINS,
        default=PLUGINS[0][0]
    )
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"


class Category(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return f"{self.name}"


class Transaction(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    type = models.CharField(
        max_length=100,
        choices=TRANSACTION_TYPES,
        default=TRANSACTION_TYPES[0][0],
    )
    amount = models.FloatField()
    account = models.ForeignKey(Account, on_delete=models.PROTECT)
    original_description = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    # nullable
    pretty_description = models.CharField(max_length=200, null=True, default=None, blank=True)
    # need to give users some way to fill in or re ledger transactions with deleted categories
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, default=None, blank=True)

    def __str__(self):
        return f"""
            {self.date}
            {self.type}
            {self.account}
            {self.amount}
            {self.original_description}
            {self.pretty_description}
            {self.category}"""


class Description(models.Model):
    """A description rule. Provides a pretty description for
    a transactions and is used to guess the correct category
    for a transaction
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    predicate = models.CharField(max_length=200, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    # TODO could make category and sub category a FK for faster lookup?

    def __str__(self):
        return f"{self.predicate}, {self.description}"


class FileUpload(models.Model):
    account_type = models.CharField(
        max_length=100,
        choices=PLUGINS,
        default=PLUGINS[0][0]
    )
    file = models.FileField()


class SeedRequest(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    descriptions_filename = models.CharField(max_length=200)
    categories_filename = models.CharField(max_length=200)
    transactions_filename = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)


class UploadSummary(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    filename = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    account = models.CharField(max_length=200)
    min_date = models.DateField()
    max_date = models.DateField()
    new = models.IntegerField()
    updated = models.IntegerField()
    duplicate = models.IntegerField()
    error = models.IntegerField()

ledgered_parent/ledgered_app/forms.py
from django import forms
from .models import *


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = FileUpload
        fields = '__all__'


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = '__all__'
        exclude = ('owner',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # read only keeps us from editing these fields in the form.
        # Doesn't seem to work with dropdowns.
        readonly_fields = [
            'date',
            'amount',
            'original_description',
            'pretty_description',
            'type',
            'account'
        ]

        # set the attributes on the form field widget for certain fields
        for field_name, field in self.fields.items():
            if field_name in readonly_fields:
                field.widget.attrs['readonly'] = True


class LedgerTransactionForm(TransactionForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(owner=user)


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = '__all__'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        exclude = ('owner',)


class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = '__all__'
        exclude = ('owner',)


class SeedRequestForm(forms.ModelForm):
    class Meta:
        model = SeedRequest
        fields = '__all__'
        exclude = ('owner',)


class UploadSummaryForm(forms.ModelForm):
    class Meta:
        model = UploadSummary
        fields = '__all__'
        exclude = ('owner',)

ledgered_parent/ledgered_app/views.py
from django.shortcuts import render, redirect

from .seeder.seeders import *
from .utils.handle_upload import handle_upload
from .forms import FileUploadForm, TransactionForm, SeedRequestForm, DescriptionForm, LedgerTransactionForm
from .models import *
from .utils.form_utils import save_form
from .configs.config import *
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
import pandas as pd
import os
import logging.config
from .dashboards.test import get_plot


logging.config.fileConfig(LOGGER_CONFIG_PATH)
logger = logging.getLogger('root')

def index(request):
    return render(request, 'ledgered_app/index.html')


@login_required
def ledger(request):
    """Entry point for categorizing new transactions."""
    context = {"num_uncategorized": get_queue_size(request.user)}
    return render(request, 'ledgered_app/ledger.html', context)


def get_queue_size(user):
    return Transaction.objects.filter(category=None, owner=user).count()


def get_pretty_description(original_description, user):
    """Uses description rules to find a matching pretty description for this original description
    First looks through all the predicate rules and returns one of those if there's a match.
    Then look for any matching description rules without a predicate and return the match with the longest
    length.
    """
    for predicate_rule in Description.objects.filter(predicate__isnull=False, owner=user):
        if predicate_rule.predicate.lower() in original_description.lower():
            return predicate_rule.description

    for rule in Description.objects.filter(predicate__isnull=True, owner=user):
        if rule.description.lower() in original_description.lower():
            return rule.description

    return None


@login_required
def ledger_queue(request):
    """Edit the category and subcategory of a transaction."""
    num_uncategorized = get_queue_size(request.user)

    # if no remaining transactions go back to ledger landing page
    if num_uncategorized == 0:
        return redirect('ledgered_app:ledger')

    # get the next transaction in the ledger queue
    next_trxn = Transaction.objects.filter(category=None, owner=request.user).first()

    # return transaction and description form for user input
    if request.method != 'POST':
        context = {"num_uncategorized": num_uncategorized}

        pretty_dscr = get_pretty_description(next_trxn.original_description, request.user)

        if pretty_dscr:
            next_trxn.pretty_description = pretty_dscr
            # use pretty description to lookup subcategory
            # could expand this to be smarter later
            prev_trxn = Transaction.objects.filter(
                owner=request.user,
                pretty_description=pretty_dscr,
                category__isnull=False
            ).first()

            if prev_trxn:
                next_trxn.category = prev_trxn.category

            context['dscr_form'] = DescriptionForm()

        # if there's no pretty description and this, description rule, for this transaction,
        # give them a head start by putting the original string in the description form box
        else:
            context['dscr_form'] = DescriptionForm({"description": next_trxn.original_description.title()})

        # here need to limit the categories to only this user
        trxn_form = LedgerTransactionForm(instance=next_trxn, user=request.user)
        context['trxn_form'] = trxn_form

        return render(request, 'ledgered_app/ledger_queue.html', context)

    # save the submitted transaction and redirect to the ledger queue
    else:
        # id from the form defined in the template
        if 'submit_transaction' in request.POST:
            trxn_form = TransactionForm(instance=next_trxn, data=request.POST)
            save_form(trxn_form, request.user)
            return redirect('ledgered_app:ledger_queue')

        # id from the form defined in the template
        elif 'submit_description' in request.POST:
            dscr_form = DescriptionForm(data=request.POST)
            save_form(dscr_form, request.user)
            return redirect('ledgered_app:ledger_queue')


@login_required
def manage(request):
    """Page to manage user data."""
    return render(request, 'ledgered_app/manage.html')


@login_required
def seed(request):
    # posting a seed request for the first time
    if request.method == 'POST':
        form = SeedRequestForm(request.POST)
        save_form(form, request.user)

        # TODO accounts per owner. This is ugly. Only add accounts of first request
        if SeedRequest.objects.all().count() == 1:
            seed_accounts()

        seed_categories(form['categories_filename'].data, request.user)
        seed_descriptions(form['descriptions_filename'].data, request.user)
        seed_transactions(form['transactions_filename'].data, request.user)
        return redirect('ledgered_app:seed')
    else:
        # populate the form with the filenames from the correct resource's folder + "none"
        def filename_options(folder):
            return [(f, f) for f in os.listdir(RESOURCE_PATH + folder) + ["none"]]

        seeds = SeedRequest.objects.filter(owner=request.user)
        form = SeedRequestForm()
        context = {
            "form": form,
            "descriptions": filename_options("descriptions"),
            "categories": filename_options("categories"),
            "transactions": filename_options("transactions"),
            "seeds": seeds
        }
        return render(request, 'ledgered_app/seed.html', context)


@login_required
def upload(request):
    """Page to upload transaction files."""

    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            file_upload = form.save(commit=False)
            handle_upload(request.FILES['file'], file_upload.account_type, request.user)
            return redirect('ledgered_app:upload')
    else:
        uploads = UploadSummary.objects.filter(owner=request.user)
        form = FileUploadForm()
        context = {
            "form": form,
            "uploads": uploads
        }

        return render(request, 'ledgered_app/upload.html', context)


@login_required
def reports(request):
    transactions = get_user_transactions(request.user)
    plot_div = get_plot(transactions)
    return render(request, "ledgered_app/reports.html", context={'plot_div': plot_div})


def get_user_transactions(user):
    user_data = []
    for t in Transaction.objects.select_related("category", "account") .filter(owner=user):
        user_data.append([t.date, t.type, t.account.name, t.amount, t.original_description, t.pretty_description, t.category.name])
    return pd.DataFrame(user_data, columns = ["date", "type", "account", "amount", "original_description", "pretty_description", "category"])


@login_required
def delete_all(request):
    # TODO give options to only delete for this user
    for model in [Transaction, Category, Description, SeedRequest, Account, UploadSummary]:
        model.objects.all().delete()

    return render(request, 'ledgered_app/delete_all.html')


@login_required
def export(request):
    columns = [
        "date",
        "type",
        "amount",
        "account",
        "original_description",
        "pretty_description",
        "category"
    ]
    transactions = Transaction.objects.all()
    logger.info(f"Number of transactions fetched for export {transactions.count()}")
    data = download_csv(request, transactions, columns)
    response = HttpResponse(data, content_type='text/csv')
    return response


class TransactionListView(ListView):
    model = Transaction

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset


class DescriptionListView(ListView):
    model = Description

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset
    

class CategoriesListView(ListView):
    model = Category

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset


class AccountListView(ListView):
    model = Account

ledgered_parent/ledgered_app/templates/ledgered_app/base.html
<style>
  .right-align {
    float: right;
  }
  .username {
    margin-right: 10px;
  }
</style>

<p>
    {% if user.is_authenticated %}
        <a href="{% url 'ledgered_app:index' %}">Home</a> -
        <a href="{% url 'ledgered_app:upload' %}">Upload</a> -
        <a href="{% url 'ledgered_app:ledger' %}">Ledger</a> -
        <a href="{% url 'ledgered_app:reports' %}">Reports</a> -
        <a href="{% url 'ledgered_app:manage' %}">Manage</a> -
        <a href="{% url 'ledgered_app:seed' %}">Seed</a> -
        <a href="{% url 'ledgered_app:export' %}">Export</a> -
        <a>DEBUG</a> -
        <a href="{% url 'ledgered_app:list_categories' %}">Categories</a> -
        <a href="{% url 'ledgered_app:list_descriptions' %}">Descriptions</a> -
        <a href="{% url 'ledgered_app:list_transactions' %}">Transactions</a> -
        <a href="{% url 'ledgered_app:list_accounts' %}">Accounts</a> -
        <a href="{% url 'ledgered_app:delete_all' %}">Nuke</a>
        <a href="{% url 'accounts:logout' %}" class="right-align">Log Out</a>
        <span class="right-align username">Hello, {{ user.username }}!</span>
    {% else %}
        <a href="{% url 'accounts:login' %}">Log in</a> -
        <a href="{% url 'accounts:register' %}">Register</a>
    {% endif %}
    <hr />
</p>

{% block content %}{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/delete_all.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<p>Deleted all data.</p>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/index.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<p>Welcome to ledgered! Stop spending money you fat FUCKING fuck.</p>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/ledger.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<p>
    You have {{ num_uncategorized }} uncategorized transactions!
    {% if num_uncategorized > 0 %}
    <a href="{% url 'ledgered_app:ledger_queue' %}">Categorize Transactions</a>
    {% endif %}
</p>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/ledger_queue.html
{% extends "ledgered_app/base.html" %}

{% block content %}

    <h2>Remaining Transactions: {{ num_uncategorized }}</h2>
    <form action="{% url 'ledgered_app:ledger_queue' %}" method='post'>
        {% csrf_token %}
        {{ trxn_form.as_p }}
        <button name="submit_transaction">Save and Continue</button>
    </form>

    <h2>Add New Description Rule</h2>
    <form action="{% url 'ledgered_app:ledger_queue' %}" method='post'>
        {% csrf_token %}
        {{ dscr_form.as_p }}
        <button name="submit_description">Add New Description Rule</button>
    </form>

    <a href="{% url 'ledgered_app:ledger' %}">Exit</a>

{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/list_accounts.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/simple_table.css' %}">
</head>
<body>
    <h1>Accounts</h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        {% for d in object_list %}
        <tr>
          <td>{{ d.name }}</td>
        </tr>
        {% empty %}
          <tr>
            <td colspan="7">No Accounts</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</body>
</html>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/list_categories.html
{% extends "ledgered_app/base.html" %}



{% block content %}
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/simple_table.css' %}">
</head>
<body>
    <h1>Categories</h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        {% for d in object_list %}
        <tr>
          <td>{{ d.name }}</td>
        </tr>
        {% empty %}
          <tr>
            <td colspan="7">No Accounts</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</body>
</html>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/list_descriptions.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/simple_table.css' %}">
</head>
<body>
    <h1>Descriptions</h1>
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th>Predicate</th>
          <th>Owner</th>
        </tr>
      </thead>
      <tbody>
        {% for d in object_list %}
        <tr>
          <td>{{ d.description }}</td>
          <td>{{ d.predicate }}</td>
          <td>{{ d.owner }}</td>
        </tr>
        {% empty %}
          <tr>
            <td colspan="7">No Descriptions</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</body>
</html>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/list_transactions.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/simple_table.css' %}">
</head>
<body>
    <h1>Transactions</h1>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Account</th>
          <th>Type</th>
          <th>Amount</th>
          <th>Original Description</th>
          <th>Pretty Description</th>
          <th>Category</th>
          <th>Owner</th>
        </tr>
      </thead>
      <tbody>
        {% for t in object_list %}
          <tr>
            <td>{{ t.date }}</td>
            <td>{{ t.account }}</td>
            <td>{{ t.type }}</td>
            <td>{{ t.amount }}</td>
            <td>{{ t.original_description }}</td>
            <td>{{ t.pretty_description }}</td>
            <td>{{ t.category }}</td>
            <td>{{ t.owner }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="7">No Transactions</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</body>
</html>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/manage.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<p>Manage your settings on this page.</p>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/reports.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<body>
    {{ plot_div|safe }}
</body>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/seed.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/simple_table.css' %}">
</head>
<body>
    <h1>Previous Seeds</h1>

    <table>
      <thead>
        <tr>
          <th>Descriptions</th>
          <th>Categories</th>
          <th>Transactions</th>
        </tr>
      </thead>
      <tbody>
        {% for d in seeds %}
        <tr>
          <td>{{ d.descriptions_filename }}</td>
          <td>{{ d.categories_filename }}</td>
          <td>{{ d.transactions_filename }}</td>
        </tr>
        {% empty %}
          <tr>
            <td colspan="7">No seeds yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <h1>Seed Request</h1>

        <form action="{% url 'ledgered_app:seed' %}" method='post'>
            {% csrf_token %}

            {{ form.name }}
            <p>{{ form.descriptions_filename.name }}</p>
            <select name="{{ form.descriptions_filename.name }}">
            {% for option in descriptions %}
              <option value="{{ option.1 }}">{{ option.0 }}</option>
            {% endfor %}
            </select>

            <p>{{ form.categories_filename.name }}</p>
            <select name="{{ form.categories_filename.name }}">
            {% for option in categories %}
              <option value="{{ option.1 }}">{{ option.0 }}</option>
            {% endfor %}
            </select>

            <p>{{ form.transactions_filename.name }}</p>
            <select name="{{ form.transactions_filename.name }}">
            {% for option in transactions %}
              <option value="{{ option.1 }}">{{ option.0 }}</option>
            {% endfor %}
            </select>

            <button name="submit">Seed</button>
        </form>

    </body>
</html>
{% endblock content %}

ledgered_parent/ledgered_app/templates/ledgered_app/upload.html
{% extends "ledgered_app/base.html" %}

{% block content %}
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/simple_table.css' %}">
</head>
<body>
    <h1>Previous Uploads</h1>

    <table>
      <thead>
        <tr>
          <th>Filename</th>
          <th>Date Added</th>
          <th>Account</th>
          <th>Min Date</th>
          <th>Max Date</th>
          <th>New</th>
          <th>Updated</th>
          <th>Duplicate</th>
          <th>Error</th>
        </tr>
      </thead>
      <tbody>
        {% for d in uploads %}
        <tr>
          <td>{{ d.filename }}</td>
          <td>{{ d.date_added }}</td>
          <td>{{ d.account }}</td>
          <td>{{ d.min_date }}</td>
          <td>{{ d.max_date }}</td>
          <td>{{ d.new }}</td>
          <td>{{ d.updated }}</td>
          <td>{{ d.duplicate }}</td>
          <td>{{ d.error }}</td>
        </tr>
        {% empty %}
          <tr>
            <td colspan="7">No Uploads yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <h1>Upload Request</h1>

    <form action="{% url 'ledgered_app:upload' %}" method='post' enctype=multipart/form-data>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Submit Upload</button>
    </form>

    </body>
</html>

{% endblock content %}